name: Releashed
version: '1.0'
main: me.nidzuhoguro.releashed.Releashed
api-version: '1.21'
authors: [ Beyley, Nidzuhoguro ]
description: Rebuild of the plugin by Beyley
website: https://github.com/Beyley/LeashPlayers
