name: Releashed
version: '2.0-ALPHA'
main: me.nidzuhoguro.releashed.Releashed
api-version: '1.21'
authors: [ Nidzuhoguro ]
description: The best player leashing plugin :3
website: https://github.com/Nidzuhoguro/Releashed
