name: Releashed
version: '1.5-26.1.2'
main: me.nidzuhoguro.releashed.Releashed
api-version: '26.1.2'
authors: [ Nidzuhoguro ]
description: The best player leashing plugin :3
website: https://github.com/Nidzuhoguro/Releashed
